# Reference: http://hexo.io/docs/configuration.html

## Basics
title: The obstacle is the path.
subtitle:
description:
author: 47billion
email: info@47billion.com
language: en
url: http://47billion.com/blog
root: /blog/
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:
source_dir: source
public_dir: public

## Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

## Category & Tag
default_category: uncategorized
category_map:
tag_map:

## Archives
archive: 2
category: 2
tag: 2

## Local Server
port: 4000
server_ip: localhost
logger: false
logger_format: dev

## Date / Time format
date_format: MMM D YYYY
time_format: H:mm:ss

## Pagination
per_page: 10
pagination_dir: page

# Feed
feed:
  type: rss2
  path: feed.xml
  limit: 20

## Disqus
disqus_shortname: 47billion

## Plugins
# plugins:
#  - hexo-local-image

theme: alex
exclude_generator:

## Deployment
deploy:
  type: github
  repository: https://github.com/47Billion/blog.git
  branch: gh-pages
